config/routes.rb
GamesExchange::Application.routes.draw do
 

  resources :users
 resources :sessions, only: [:new, :create, :destroy]
 resources :games, only: [:create, :destroy]

 
  
  root to: 'static_pages#home'

  match '/signup',   to: 'users#new',    via: 'get'
  match '/signin',   to: 'sessions#new',    via: 'get'
  match '/signout',  to: 'sessions#destroy', via: :delete
  
 match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  

  
  
  
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
 default_scope -> { order('created_at DESC') }
 validates :user_id, presence: true
 
   validates :name, presence: true, length: { maximum: 140 }
   validates :location, presence: true, length: { maximum: 140 }
   validates :console, length: { maximum: 140 }
 
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
   before_action :signed_in_user, only: [:create, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.build(game_params)
	@games = Game.all
    if @game.save
      flash[:success] = "Game Added!"
      redirect_to root_path
    else
	 @feed_items = []
      render 'static_pages/home'
    end
	
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :platform, :location)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<li>
  <span class="name"><%= game.name %></span>
  <span class="console"><%= game.console %></span>
  <span class="location"><%= game.location %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(game.created_at) %> ago.
  </span>
</li>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Platform</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.game %></td>
        <td><%= game.platform %></td>
        <td><%= game.user_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game.game %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @game.platform %>
</p>

<p>
  <strong>User:</strong>
  <%= @game.user_id %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>